# Generated by Django 4.0 on 2021-12-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
                ('mgrid', models.CharField(max_length=10)),
                ('dept_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('slipno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('basic_salary', models.FloatField()),
                ('hra', models.FloatField()),
                ('conveyance_allowance', models.FloatField()),
                ('medical_allowance', models.FloatField()),
                ('performance_bonus', models.FloatField()),
                ('others', models.FloatField()),
                ('sdate', models.DateField()),
                ('dno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.department')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.employee')),
            ],
        ),
    ]
