# Generated by Django 4.0 on 2021-12-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='sdate',
            field=models.DateField(),
        ),
    ]
