# Generated by Django 4.0 on 2021-12-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='dedid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salary',
            name='slipno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
