# Generated by Django 4.0 on 2021-12-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('salary', '0002_alter_deduction_dedid_alter_salary_slipno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.employee'),
        ),
    ]
