# Generated by Django 4.0 on 2021-12-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_salary_sdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='slipno',
        ),
    ]
