# Generated by Django 4.0 on 2021-12-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salary', '0003_alter_department_mgrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('dedid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ded_date', models.DateField()),
                ('dcategory', models.CharField(choices=[('P', 'Pension'), ('L', 'Loans')], max_length=1)),
                ('damt', models.FloatField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
