# Generated by Django 4.0 on 2021-12-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_remove_deduction_slipno'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='slipno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='salary.salary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='sdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
