# Generated by Django 4.0 on 2021-12-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_delete_accountant'),
        ('salary', '0004_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('eid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authenticate.employee')),
                ('slipno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salary.salary')),
            ],
        ),
    ]
