# Generated by Django 4.0 on 2021-12-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_alter_deduction_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='conveyance_allowance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='medical_allowance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='others',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='performance_bonus',
            field=models.FloatField(null=True),
        ),
    ]
