# Generated by Django 4.0 on 2021-12-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_deduction_slipno_alter_salary_sdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='slipno',
        ),
        migrations.AlterField(
            model_name='salary',
            name='sdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
